#!/bin/bash --norc
# Copyright Verizon Media Inc.
# Copyright 2020, Verizon Media Inc.
# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache-2.0 license.
# See LICENSE file in https://github.com/yahoo/PrivacyChain-sdk-c++/blob/master/LICENSE for terms.
#
# Wait ... Wut?  this is the "easy" version?  Rly?
#
# The full nearby build for developers
#
#   buildconf
#   configure
#   make [all]
#   make check
#
# debugging ...
#
#   enable_dependency_tracking=no ./maintenance/nearby 
#
# Usage:
#
#   ./maintenance/nearby     (no options)
#
# Usage:
#
#   prefix=/exp/iab/privacychain \
#   with_std_tunitas=/opt/tunitas \
#   with_temerarious_flagship=/opt/tunitas \
#   ./maintenance/nearby
# 
# Usage:
#
#   prefix=/exp/iab/privacychain \
#   with_std_tunitas=no \
#   with_tunitas_basics=/build/tunitas/tunitas-basics \
#   with_temerarious_flagship=/build/tunitas/temerarious-flagship \
#   ./maintenance/nearby
#
# /opt/scold              - The S.C.O.L.D. module "with" variables default.
# /opt/tunitas            - The Tunitas "with" variables default.
# /opt/hyperledger/fabric - The Hyperledger Fabric "with" variables default.
# /opt/iab/privacychain   - The IAB PrivacyChain "with" variables default.
#
cd ${0%/*}/.. || exit 70
: ${prefix:=/exp/iab/privacychain}
: ${with_siblings:=${PWD%/*}}
: ${with_submodules:=no}
# with_external is deprecated, it was used by hypogeal-twilight in 0.4 (oh point four)? (... uh 0.42?)
if [[ -d ${PWD%/*}/nearby ]] && [[ -z $with_nearby ]] ; then
    : ${with_nearby:=${PWD%/*}/nearby} # all the development copies are in a single .../nearby area
    : ${with_tunitas_nearby:=${with_nearby?}}
    : ${with_scold_nearby:=${with_nearby?}}
    : ${with_fabric_nearby:=${with_nearby?}}
    # and the "standard" areas are not available, each development area myst be specified in turn, individually
    : ${with_std_scold:=/opt/scold}
    : ${with_std_tunitas:=/exp/tunitas}
    : ${with_std_state_space:=/exp/state-space}
elif [[ -d /build ]] ; then
    : ${with_build:=/build} # every major component source is spread out in its own development tree
else
    : ${with_build:=${with_opt:-/opt}}
fi
: ${with_state_space_nearby:=${with_build?}/state-space}
: ${with_tunitas_nearby:=${with_build?}/tunitas}
: ${with_scold_nearby:=${with_nearby:-${with_build?}/scold}} # with_nearby is with_scold_nearby
if [[ -d ${with_build?}/others/Hyperledger/Fabric/fabric-sdk-c++ ]] ; then
    : ${with_fabric_nearby:=${with_build?}/others/Hyperledger/Fabric} # this is an exotic and unexpected location
    echo REMINDER choosing with_fabric_nearby=${with_fabric_nearby} 1>&2
else
    : ${with_fabric_nearby:=${with_siblings?}}
fi
# and the "standard" areas are not available, each development area myst be specified in turn, individually
# [[FIXTHIS]] these should become named s/std_/opt_/g as the --std- prefix has become misdirecting
: ${with_std_scold:=/opt/scold}
: ${with_std_tunitas:=/exp/tunitas}
: ${with_std_state_space:=/exp/state-space}
: ${with_std_hyperledger_fabric:=$with_fabric_nearby}
# These need to match 1-for-1 the enablements in configure.ac
: ${with_hyperledger_fabric_sdk:=${with_fabric_nearby?}/fabric-sdk-c++}
: with_hyperledger_fabric_db -- the database itself
: with_hyperledger_fabric_ca -- the administrator
: with_hyperledger_fabric_user -- the user-role database
: with_hyperledger_fabric -- the client interface
: with_hyperledger -- the general facilities
: ${with_hypogeal_twilight:=${with_scold_nearby?}/hypogeal-twilight}
: ${with_incendiary_sophist:=${with_scold_nearby?}/incendiary-sophist}
: ${with_module_json:=${with_scold_nearby?}/module-json}
if [[ -d ${with_scold_nearby?}/module-langu} ]] ; then : ${with_module_langu:=${with_scold_nearby?}/module-langu} ; fi
: ${with_module_nonstd:=${with_scold_nearby?}/module-nonstd}
: ${with_module_posix:=${with_scold_nearby?}/module-posix}
: ${with_module_rabinpoly:=${with_scold_nearby?}/module-rabinpoly}
: ${with_module_rigging:=${with_scold_nearby?}/module-rigging}
: ${with_module_shell:=${with_scold_nearby?}/module-shell}
: ${with_module_std:=${with_scold_nearby?}/module-std}
: ${with_module_string:=${with_scold_nearby?}/module-string}
: ${with_module_sys:=${with_scold_nearby?}/module-sys}
#
: ${with_state_space_fabric_sdk:=${with_siblings?}/fabric-sdk-c++}
: ${with_temerarious_flagship:=${with_tunitas_nearby?}/temerarious-flagship}
: ${with_tunitas_basics:=${with_tunitas_nearby?}/basics}
: ${with_tunitas_butano:=${with_tunitas_nearby?}/butano}
: ${CPPFLAGS:=-Wno-cpp}
: ${CXXFLAGS:=-Wno-attributes -Wno-deprecated-declarations}
: ${LDFLAGS:=-O0 -ggdb}
eval \
    ${prefix:+prefix=$prefix} \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ${with_temerarious_flagship:+with_temerarious_flagship=$with_temerarious_flagship} \
    ./buildconf &&
./configure \
    ${prefix:+--prefix=$prefix} \
    --disable-mock-build \
    ${enable_configure_verbose:+--enable-dependency-tracking=$enable_configure_verbose} \
    ${enable_configure_debug:+--enable-dependency-tracking=$enable_configure_debug} \
    ${enable_dependency_tracking:+--enable-dependency-tracking=$enable_dependency_tracking} \
    ${with_scold_nearby:+--with-nearby=$with_scold_nearby} ${with_external:+--with-external=$with_external} \
    ${with_submodules:+--with-submodules=$with_submodules} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_hyperledger_fabric_sdk:+--with-hyperledger-fabric-sdk=$with_hyperledger_fabric_sdk} \
    ${with_hyperledger_fabric_db:+--with-hyperledger-fabric-db=$with_hyperledger_fabric_db} \
    ${with_hyperledger_fabric_ca:+--with-hyperledger-fabric-ca=$with_hyperledger_fabric_ca} \
    ${with_hyperledger_fabric:+--with-hyperledger-fabric=$with_hyperledger_fabric} \
    ${with_hyperledger:+--with-hyperledger-fabric=$with_hyperledger} \
    ${with_incendiary_sophist:+--with-incendiary-sophist=$with_incendiary_sophist} \
    ${with_module_json:+--with-module-json=$with_module_json} \
    ${with_module_langu:+--with-module-langu=$with_module_langu} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rabinpoly:+--with-module-rabinpoly=$with_module_rabinpoly} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_shell:+--with-module-shell=$with_module_shell} \
    ${with_module_std:+--with-module-std=$with_module_std} \
    ${with_module_string:+--with-module-string=$with_module_string} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    ${with_state_space_fabric_sdk:+--with-state-space-fabric-sdk=$with_state_space_fabric_sdk} \
    ${with_tunitas_basics:+--with-tunitas-basics=$with_tunitas_basics} \
    ${with_tunitas_butano:+--with-tunitas-butano=$with_tunitas_butano} \
    ${with_temerarious_flagship:+--with-temerarious-flagship=$with_temerarious_flagship} \
    ${with_std_hyperledger_fabric:+--with-std-hyperledger-fabric=$with_std_hyperledger_fabric} \
    ${with_std_tunitas:+--with-std-tunitas=$with_std_tunitas} \
    ${UNUSED_with_std_state_space:+--with-std-state-space=$with_std_state_space} \
    ${with_std_scold:+--with-std-scold=$with_std_scold} \
    ${end} &&
make ${CPPFLAGS:+CPPFLAGS="$CPPFLAGS"} ${CXXFLAGS:+CXXFLAGS="$CXXFLAGS"} ${LDFLAGS:+LDFLAGS="$LDFLAGS"} &&
make check ${CPPFLAGS:+CPPFLAGS="$CPPFLAGS"} ${CXXFLAGS:+CXXFLAGS="$CXXFLAGS"} ${LDFLAGS:+LDFLAGS="$LDFLAGS"} &&
echo OK DONE
